runtime: nodejs18
env: standard

handlers:
  # Serve the index.html for all routes
  - url: /.*  # This handles all routes, including /admin, /about, etc.
    static_files: dist/index.html
    upload: dist/index.html

  # Serve static files (CSS, JS, images) for all other requests
  - url: /static
    static_dir: dist/static

  # - url: /
  #   static_dir: dist

